const statesLGAs = {
"Abia":["Aba North","Aba South","Arochukwu","Bende","Ikwuano","Isiala Ngwa North","Isiala Ngwa South","Isuikwuato","Obi Ngwa","Ohafia","Osisioma","Ugwunagbo","Ukwa East","Ukwa West","Umuahia North","Umuahia South","Umu Nneochi"],
"Adamawa":["Demsa","Fufore","Ganye","Gayuk","Gombi","Grie","Hong","Jada","Lamurde","Madagali","Maiha","Mayo-Belwa","Michika","Mubi North","Mubi South","Numan","Shelleng","Song","Toungo","Yola North","Yola South"],
"Akwa Ibom":["Abak","Eastern Obolo","Eket","Esit Eket","Essien Udim","Etim Ekpo","Etinan","Ibeno","Ibesikpo Asutan","Ibiono-Ibom","Ika","Ikono","Ikot Abasi","Ikot Ekpene","Ini","Itu","Mbo","Mkpat-Enin","Nsit-Atai","Nsit-Ibom","Nsit-Ubium","Obot Akara","Okobo","Onna","Oron","Oruk Anam","Udung-Uko","Ukanafun","Uruan","Urue-Offong/Oruko","Uyo"],
"Anambra":["Aguata","Anambra East","Anambra West","Anaocha","Awka North","Awka South","Ayamelum","Dunukofia","Ekwusigo","Idemili North","Idemili South","Ihiala","Njikoka","Nnewi North","Nnewi South","Ogbaru","Onitsha North","Onitsha South","Orumba North","Orumba South","Oyi"],
"Bauchi":["Alkaleri","Bauchi","Bogoro","Damban","Darazo","Dass","Gamawa","Ganjuwa","Giade","Itas/Gadau","Jama'are","Katagum","Kirfi","Misau","Ningi","Shira","Tafawa Balewa","Toro","Warji","Zaki"],
"Bayelsa":["Brass","Ekeremor","Kolokuma/Opokuma","Nembe","Ogbia","Sagbama","Southern Ijaw","Yenagoa"],
"Benue":["Ado","Agatu","Apa","Buruku","Gboko","Guma","Gwer East","Gwer West","Katsina-Ala","Konshisha","Kwande","Logo","Makurdi","Obi","Ogbadibo","Ohimini","Oju","Okpokwu","Oturkpo","Tarka","Ukum","Ushongo","Vandeikya"],
"Borno":["Abadam","Askira/Uba","Bama","Bayo","Biu","Chibok","Damboa","Dikwa","Gubio","Guzamala","Gwoza","Hawul","Jere","Kaga","Kala/Balge","Konduga","Kukawa","Kwaya Kusar","Mafa","Magumeri","Maiduguri","Marte","Mobbar","Monguno","Ngala","Nganzai","Shani"],
"Cross River":["Abi","Akamkpa","Akpabuyo","Bakassi","Bekwarra","Biase","Boki","Calabar Municipal","Calabar South","Etung","Ikom","Obanliku","Obubra","Obudu","Odukpani","Ogoja","Yakuur","Yala"],
"Delta":["Aniocha North","Aniocha South","Bomadi","Burutu","Ethiope East","Ethiope West","Ika North East","Ika South","Isoko North","Isoko South","Ndokwa East","Ndokwa West","Okpe","Oshimili North","Oshimili South","Patani","Sapele","Udu","Ughelli North","Ughelli South","Ukwuani","Uvwie","Warri North","Warri South","Warri South West"],
"Ebonyi":["Abakaliki","Afikpo North","Afikpo South","Ebonyi","Ezza North","Ezza South","Ikwo","Ishielu","Ivo","Izzi","Ohaozara","Ohaukwu","Onicha"],
"Edo":["Akoko-Edo","Egor","Esan Central","Esan North-East","Esan South-East","Esan West","Etsako Central","Etsako East","Etsako West","Igueben","Ikpoba Okha","Orhionmwon","Oredo","Ovia North-East","Ovia South-West","Owan East","Owan West","Uhunmwonde"],
"Ekiti":["Ado Ekiti","Efon","Ekiti East","Ekiti South-West","Ekiti West","Emure","Gbonyin","Ido Osi","Ijero","Ikere","Ikole","Ilejemeje","Irepodun/Ifelodun","Ise/Orun","Moba","Oye"],
"Enugu":["Aninri","Awgu","Enugu East","Enugu North","Enugu South","Ezeagu","Igbo Etiti","Igbo Eze North","Igbo Eze South","Isi Uzo","Nkanu East","Nkanu West","Nsukka","Oji River","Udenu","Udi","Uzo-Uwani"],
"FCT":["Abaji","Bwari","Gwagwalada","Kuje","Kwali","Municipal Area Council"],
"Gombe":["Akko","Balanga","Billiri","Dukku","Funakaye","Gombe","Kaltungo","Kwami","Nafada","Shongom","Yamaltu/Deba"],
"Imo":["Aboh Mbaise","Ahiazu Mbaise","Ehime Mbano","Ezinihitte","Ideato North","Ideato South","Ihitte/Uboma","Ikeduru","Isiala Mbano","Isu","Mbaitoli","Ngor Okpala","Njaba","Nkwerre","Nwangele","Obowo","Oguta","Ohaji/Egbema","Okigwe","Orlu","Orsu","Oru East","Oru West","Owerri Municipal","Owerri North","Owerri West","Unuimo"],
"Jigawa":["Auyo","Babura","Biriniwa","Birnin Kudu","Buji","Dutse","Gagarawa","Garki","Gumel","Guri","Gwaram","Gwiwa","Hadejia","Jahun","Kafin Hausa","Kaugama","Kazaure","Kiri Kasama","Kiyawa","Maigatari","Malam Madori","Miga","Ringim","Roni","Sule Tankarkar","Taura","Yankwashi"],
"Kaduna":["Birnin Gwari","Chikun","Giwa","Igabi","Ikara","Jaba","Jema'a","Kachia","Kaduna North","Kaduna South","Kagarko","Kajuru","Kaura","Kauru","Kubau","Kudan","Lere","Makarfi","Sabon Gari","Sanga","Soba","Zangon Kataf","Zaria"],
"Kano":["Ajingi","Albasu","Bagwai","Bebeji","Bichi","Bunkure","Dala","Dambatta","Dawakin Kudu","Dawakin Tofa","Doguwa","Fagge","Gabasawa","Garko","Garun Mallam","Gaya","Gezawa","Gwale","Gwarzo","Kabo","Kano Municipal","Karaye","Kibiya","Kiru","Kumbotso","Kunchi","Kura","Madobi","Makoda","Minjibir","Nasarawa","Rano","Rimin Gado","Rogo","Shanono","Sumaila","Takai","Tarauni","Tofa","Tsanyawa","Tudun Wada","Ungogo","Warawa","Wudil"],
"Katsina":["Bakori","Batagarawa","Batsari","Baure","Bindawa","Charanchi","Dandume","Danja","Dan Musa","Daura","Dutsi","Dutsin Ma","Faskari","Funtua","Ingawa","Jibia","Kafur","Kaita","Kankara","Kankia","Katsina","Kurfi","Kusada","Mai'Adua","Malumfashi","Mani","Mashi","Matazu","Musawa","Rimi","Sabuwa","Safana","Sandamu","Zango"],
"Kebbi":["Aleiro","Arewa Dandi","Argungu","Augie","Bagudo","Birnin Kebbi","Bunza","Dandi","Fakai","Gwandu","Jega","Kalgo","Koko/Besse","Maiyama","Ngaski","Sakaba","Shanga","Suru","Wasagu/Danko","Yauri","Zuru"],
"Kogi":["Adavi","Ajaokuta","Ankpa","Bassa","Dekina","Ibaji","Idah","Igalamela Odolu","Ijumu","Kabba/Bunu","Kogi","Lokoja","Mopa Muro","Ofu","Ogori/Magongo","Okehi","Okene","Olamaboro","Omala","Yagba East","Yagba West"],
"Kwara":["Asa","Baruten","Edu","Ekiti","Ifelodun","Ilorin East","Ilorin South","Ilorin West","Irepodun","Isin","Kaiama","Moro","Offa","Oke Ero","Oyun","Pategi"],
"Lagos":["Agege","Ajeromi-Ifelodun","Alimosho","Amuwo-Odofin","Apapa","Badagry","Epe","Eti Osa","Ibeju-Lekki","Ifako-Ijaiye","Ikeja","Ikorodu","Kosofe","Lagos Island","Lagos Mainland","Mushin","Ojo","Oshodi-Isolo","Shomolu","Surulere"],
"Nasarawa":["Akwanga","Awe","Doma","Karu","Keana","Keffi","Kokona","Lafia","Nasarawa","Nasarawa Egon","Obi","Toto","Wamba"],
"Niger":["Agaie","Agwara","Bida","Borgu","Bosso","Chanchaga","Edati","Gbako","Gurara","Katcha","Kontagora","Lapai","Lavun","Magama","Mariga","Mashegu","Mokwa","Moya","Paikoro","Rafi","Rijau","Shiroro","Suleja","Tafa","Wushishi"],
"Ogun":["Abeokuta North","Abeokuta South","Ado-Odo/Ota","Egbado North","Egbado South","Ewekoro","Ifo","Ijebu East","Ijebu North","Ijebu North East","Ijebu Ode","Ikenne","Imeko Afon","Ipokia","Obafemi Owode","Odeda","Odogbolu","Ogun Waterside","Remo North","Shagamu"],
"Ondo":["Akoko North-East","Akoko North-West","Akoko South-West","Akoko South-East","Akure North","Akure South","Ese Odo","Idanre","Ifedore","Ilaje","Ile Oluji/Okeigbo","Irele","Odigbo","Okitipupa","Ondo East","Ondo West","Ose","Owo"],
"Osun":["Atakunmosa East","Atakunmosa West","Aiyedaade","Aiyedire","Boluwaduro","Boripe","Ede North","Ede South","Ife Central","Ife East","Ife North","Ife South","Egbedore","Ejigbo","Ifedayo","Ifelodun","Ila","Ilesa East","Ilesa West","Irepodun","Irewole","Isokan","Iwo","Obokun","Odo Otin","Ola Oluwa","Olorunda","Oriade","Orolu","Osogbo"],
"Oyo":["Afijio","Akinyele","Atiba","Atisbo","Egbeda","Ibadan North","Ibadan North-East","Ibadan North-West","Ibadan South-East","Ibadan South-West","Ibarapa Central","Ibarapa East","Ibarapa North","Ido","Irepo","Iseyin","Itesiwaju","Iwajowa","Kajola","Lagelu","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole","Ona Ara","Orelope","Ori Ire","Oyo","Oyo East","Saki East","Saki West","Surulere"],
"Plateau":["Barkin Ladi","Bassa","Bokkos","Jos East","Jos North","Jos South","Kanam","Kanke","Langtang South","Langtang North","Mangu","Mikang","Pankshin","Qua'an Pan","Riyom","Shendam","Wase"],
"Rivers":["Abua/Odual","Ahoada East","Ahoada West","Akuku-Toru","Andoni","Asari-Toru","Bonny","Degema","Eleme","Emohua","Etche","Gokana","Ikwerre","Khana","Obio/Akpor","Ogba/Egbema/Ndoni","Ogu/Bolo","Okrika","Omuma","Opobo/Nkoro","Oyigbo","Port Harcourt","Tai"],
"Sokoto":["Binji","Bodinga","Dange Shuni","Gada","Goronyo","Gudu","Gwadabawa","Illela","Isa","Kebbe","Kware","Rabah","Sabon Birni","Shagari","Silame","Sokoto North","Sokoto South","Tambuwal","Tangaza","Tureta","Wamako","Wurno","Yabo"],
"Taraba":["Ardo Kola","Bali","Donga","Gashaka","Gassol","Ibi","Jalingo","Karim Lamido","Kumi","Lau","Sardauna","Takum","Ussa","Wukari","Yorro","Zing"],
"Yobe":["Bade","Bursari","Damaturu","Fika","Fune","Geidam","Gujba","Gulani","Jakusko","Karasuwa","Machina","Nangere","Nguru","Potiskum","Tarmuwa","Yunusari","Yusufari"],
"Zamfara":["Anka","Bakura","Birnin Magaji/Kiyaw","Bukkuyum","Bungudu","Gummi","Gusau","Kaura Namoda","Maradun","Maru","Shinkafi","Talata Mafara","Chafe","Zurmi"]
};
const industries=["Agriculture & Agribusiness","Automotive & Transportation","Beauty, Spa & Personal Care","Construction & Real Estate","Consulting & Professional Services","Education & Training","Energy, Power & Solar","Entertainment, Media & Creative","Fashion & Apparel","Financial Services & Fintech","Food & Beverage","Healthcare & Medical","Hospitality & Tourism","ICT, Software & Technology","Import / Export & Trading","Legal Services","Logistics & Delivery","Manufacturing","NGO / Nonprofit / Association","Oil & Gas","Retail & E-commerce","Security Services","Telecommunications","Wholesale & Distribution","Other"];
const stateNames=Object.keys(statesLGAs).sort();
const data={}; let step=0;
const steps=[
{title:"Registration details",html:()=>`<div class="field"><label>Business name</label><input id="businessName" value="${data.businessName||''}" placeholder="Registered business name"></div><div class="field"><label>CAC registration number</label><input id="cacNumber" value="${data.cacNumber||''}" placeholder="BN / RC / IT number"></div><div class="field"><label>Business type</label><select id="businessType"><option value="">Select business type</option>${["Business Name","Limited Liability Company","Incorporated Trustees / NGO","Other"].map(x=>`<option ${data.businessType===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Registration date</label><input type="date" id="registrationDate" value="${data.registrationDate||''}"></div>`},
{title:"Business profile",html:()=>`<div class="field"><label>Industry / sector</label><select id="industry"><option value="">Select industry / sector</option>${industries.map(x=>`<option ${data.industry===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>State of operation</label><select id="state"><option value="">Select state</option>${stateNames.map(x=>`<option ${data.state===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>LGA</label><select id="lga"><option value="">Select LGA</option></select></div><div class="field"><label>Number of employees</label><select id="employees"><option value="">Select employee range</option>${["0 (No employees)","1–5","6–20","21–50","51–100","101+"].map(x=>`<option ${data.employees===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Estimated annual turnover range</label><select id="turnover"><option value="">Select turnover range</option>${["Under ₦1 million","₦1m–₦5m","₦5m–₦25m","₦25m–₦100m","₦100m–₦500m","Above ₦500m","Prefer not to say"].map(x=>`<option ${data.turnover===x?'selected':''}>${x}</option>`).join('')}</select></div>`},
{title:"Tax",html:()=>questions([["tin","Do you have a Tax Identification Number?"],["taxRegistered","Are your relevant tax registrations in place?"],["taxUpToDate","Are your tax obligations up to date?"]])},
{title:"CAC compliance",html:()=>questions([["annualReturns","Are your CAC annual returns up to date?"],["recordsUpdated","Are changes to your business information properly reflected in your CAC records?"],["cacDocs","Do you have your key CAC documents available and current?"]])},
{title:"Licences & permits",html:()=>questions([["regulated","Does your business operate in a regulated industry?"],["permits","If licences or permits apply to your business, are they current?"]])},
{title:"Brand protection",html:()=>`<div class="field"><label>How is your brand currently protected?</label><select id="trademark"><option value="">Select one</option>${["Trademark registered","Trademark application in progress","Not registered","Not sure"].map(x=>`<option ${data.trademark===x?'selected':''}>${x}</option>`).join('')}</select></div>`},
{title:"Employees & HR",html:()=>`<div class="field"><label>Do you have employees?</label><select id="hasEmployees"><option value="">Select one</option><option ${data.hasEmployees==='Yes'?'selected':''}>Yes</option><option ${data.hasEmployees==='No'?'selected':''}>No</option></select></div><div class="field" id="hrWrap"><label>Are your basic employee/HR compliance records in place?</label><select id="hr"><option value="">Select one</option>${["Yes","No","Not sure"].map(x=>`<option ${data.hr===x?'selected':''}>${x}</option>`).join('')}</select></div>`}
];
function questions(items){return items.map(([id,label])=>`<div class="field"><label>${label}</label><select id="${id}"><option value="">Select one</option>${["Yes","No","Not sure"].map(x=>`<option ${data[id]===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}
function render(){document.getElementById('stepContent').innerHTML=`<h2 style="font-size:2rem">${steps[step].title}</h2>${steps[step].html()}`;document.getElementById('stepCounter').textContent=`Step ${step+1} of ${steps.length}`;document.getElementById('progressBar').style.width=`${((step+1)/steps.length)*100}%`;document.getElementById('backBtn').style.visibility=step===0?'hidden':'visible';document.getElementById('nextBtn').textContent=step===steps.length-1?'See My Result →':'Continue →';if(step===1){const s=document.getElementById('state'),l=document.getElementById('lga');function load(){const list=statesLGAs[s.value]||[];l.innerHTML=`<option value="">Select LGA</option>`+list.map(x=>`<option ${data.lga===x?'selected':''}>${x}</option>`).join('')}s.addEventListener('change',()=>{data.lga='';load()});load()}if(step===6){const has=document.getElementById('hasEmployees'),wrap=document.getElementById('hrWrap');function toggle(){wrap.style.display=has.value==='No'?'none':'block'}has.addEventListener('change',toggle);toggle()}}
function save(){document.querySelectorAll('#stepContent input,#stepContent select').forEach(el=>data[el.id]=el.value)}
function status(key){const v=data[key];if(v==='Yes'||v==='Trademark registered'||v==='Trademark application in progress')return'ok';if(v==='No'||v==='Not registered')return'bad';if(v==='Not sure')return'warn';return'na'}
function calculate(){let checks=['tin','taxRegistered','taxUpToDate','annualReturns','recordsUpdated','cacDocs','permits'];if(data.hasEmployees==='Yes')checks.push('hr');let points=0,max=checks.length*2;checks.forEach(k=>{const s=status(k);if(s==='ok')points+=2;else if(s==='warn')points+=1});const ts=status('trademark');max+=2;if(ts==='ok')points+=2;else if(ts==='warn')points+=1;return Math.round((points/max)*100)}
function showResults(){const score=calculate();const rows=[['Business Registration',data.cacNumber?'ok':'warn'],['Tax Compliance',[status('tin'),status('taxRegistered'),status('taxUpToDate')].includes('bad')?'bad':[status('tin'),status('taxRegistered'),status('taxUpToDate')].includes('warn')?'warn':'ok'],['CAC Compliance',[status('annualReturns'),status('recordsUpdated'),status('cacDocs')].includes('bad')?'bad':[status('annualReturns'),status('recordsUpdated'),status('cacDocs')].includes('warn')?'warn':'ok'],['Licences & Permits',status('permits')],['Trademark / Brand Protection',status('trademark')],['HR Compliance',data.hasEmployees==='No'?'na':status('hr')]];const labels={ok:'Complete',warn:'Attention Needed',bad:'Action Required',na:'Not Assessed'};document.getElementById('assessmentFormView').hidden=true;const view=document.getElementById('resultsView');view.hidden=false;view.innerHTML=`<div class="results-head"><div class="score-ring" style="--score:${score}%"><strong>${score}/100</strong></div><div><span class="eyebrow" style="color:#a16e00">YOUR FUTUREPROOF SCORE</span><h2 style="font-size:2.4rem;margin:10px 0">${score>=75?'Your profile looks relatively strong.':score>=50?'Some areas may need attention.':'Several areas may require review.'}</h2><p>This is an informational assessment based only on the answers you provided.</p></div></div><div class="result-list">${rows.map(([n,s])=>`<div class="result-item"><b>${n}</b><span class="status ${s}">${labels[s]}</span></div>`).join('')}</div><div class="note" style="margin-top:24px">Your FUTUREPROOF Score is not an official government compliance rating, legal opinion or tax opinion. Requirements can vary by business type, sector, location and circumstances.</div><div class="actions"><a class="btn btn-gold" href="get-help.html#ticket">Submit a Support Ticket</a><a class="btn btn-dark" href="${wa(`Hello FUTUREPROOF, I completed the Business Compliance Assessment for ${data.businessName||'my business'} and my score is ${score}/100. I would like help reviewing the areas that need attention.`)}" target="_blank">WhatsApp FUTUREPROOF</a><button class="btn btn-light" id="restartBtn">Retake Assessment</button></div>`;document.getElementById('restartBtn').onclick=()=>location.reload()}
document.getElementById('nextBtn').onclick=()=>{save();if(step<steps.length-1){step++;render()}else showResults()};document.getElementById('backBtn').onclick=()=>{save();if(step>0){step--;render()}};render();
